### ISSUE TITLE
Spack env vars persist in the crayenv environment

### ISSUE THREAD

**Issue by roryck** [NCAR/spack-gust#10]
After doing

module --force purge
module crayenv/22.08
module load cray-netcdf/4.8.1.5

Environment variables from the spack environment persist, e.g.

env | grep NETCDF
NETCDF=/glade/u/apps/gust/22.08/spack/opt/spack/netcdf/4.8.1/cce/14.0.2/q5m7ztl

All the NCAR_ variables and so on also persist. It would probably make the crayenv cleaner if we restored the environment to a pre-ncarenv state.

**Comment by vanderwb** [comment]
Hmm. This certainly isn't intentional. Seems like an Lmod bug.

**Comment by vanderwb** [comment]
@roryck Are you still able to reproduce this behavior? This is what I get:
```
[00:19] ~$ module reset
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None
[00:19] ~$ echo $NETCDF
/glade/u/apps/gust/22.08b/spack/opt/spack/netcdf/4.8.1/cce/14.0.2
[00:19] ~$ module --force purge
[00:19] ~$ ml crayenv
[00:19] ~$ echo $NETCDF

[00:19] ~$
```

**Comment by roryck** [comment]
Seems fixed to me, I don't get the space vars persisting in the crayenv now

**Comment by vanderwb** [comment]
Excellent - thanks for confirming.
