### ISSUE TITLE
MKL Request

### ISSUE THREAD

**Issue by benkirk** [NCAR/spack-gust#11]
Jim Edwards requests MKL for evaluation (https://ncarhpcusergroup.slack.com/archives/C0408SWRUDN/p1661450622794189),

I would guess this might fit as a 'singleton' below the compiler variants, but @vanderwb clearly your call!

**Comment by vanderwb** [comment]
@jedwards4b Installed. Let me know here if you encounter problems. I'm assuming Spack set the module up correctly.

**Comment by jedwards4b** [comment]
Looks good, thank you.
