### ISSUE TITLE
Request ncview

### ISSUE THREAD

**Issue by jsauer-NCAR** [NCAR/spack-gust#13]
Request to add ncview to gust for quick/convenient viewing of netCDF files created there.

**Comment by vanderwb** [comment]
Got it, Jeremy. I'll look into installing it this weekend. Probably looking at redeploying the whole stack so it'll get included in the new deployment. Hopefully will be ready for Monday.

**Comment by vanderwb** [comment]
@jsauer-NCAR Thanks for your patience. This is finally installed! Ran into some build issues when using Spack to install it, but those should be resolved.

**Comment by jsauer-NCAR** [comment]
Just had a go with it and it works as expected for me. Thanks!
