### ISSUE TITLE
runtime error with intel

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/spack-gust#15]
Currently Loaded Modules:
  1) ncarenv/22.08b (S)   3) cmake/3.23.2        5) cray-mpich/8.1.18       7) hdf5-mpi/1.12.2    9) pnetcdf/1.12.2
  2) intel/2022.1.0       4) craype/2.7.17 (S)   6) cray-libsci/22.08.1.1   8) netcdf-mpi/4.8.1

  Where:
   S:  Module is Sticky, requires --force to unload or purge

 gu0001.hsn.gu.hpc.ucar.edu 5: /var/run/palsd/f8d85d3f-82f8-4b10-82c3-544264d60e4c/files/cesm.exe: error while loading shared libraries: libnetcdff.so.7: cannot open shared object file: No such file or directory

**Comment by vanderwb** [comment]
`ncarcompilers` wasn't loaded, so RPATH'ing of netCDF wasn't happening.
