### ISSUE TITLE
Can bypass ncarwrapper by reloading craype

### ISSUE THREAD

**Issue by vanderwb** [NCAR/spack-gust#17]
Even though *stickyness* should prevent `craype` from appearing later in the module list than `ncarcompilers`, Lmod has no compulsions about reloading the module and breaking the order. Need to find a more robust solution for wrapper precedence.
```
[10:04] 14.0.2$ module reset
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None
[10:04] 14.0.2$ which ftn
/glade/u/apps/gust/22.08/spack/opt/spack/ncarcompilers/0.6.2/cce/14.0.2/l36yrnc/bin/ftn
[10:04] 14.0.2$ ml craype
[10:04] 14.0.2$ which ftn
/opt/cray/pe/craype/2.7.17/bin/ftn
```

**Comment by vanderwb** [comment]
This should no longer be possible as of [94ee37f](https://github.com/NCAR/spack-gust/commit/94ee37f613de45914aabb82023c7cd10d65213c1).

@jedwards4b - you shouldn't need to be careful about module load order any more for wrapper precedence.

**Comment by benkirk** [comment]
@vanderwb could (should?) `ncarcompilers` depend on `craype` at the module level, presumably forcing the ordering?  Or are there going to be use cases for `ncarcompilers` without the underlying `craype`??

Anyway, question may be moot since it looks like you have a fix...

**Comment by vanderwb** [comment]
I think there may be cases in which a user wants to completely separate themselves from the Cray stack and I'd like to keep that option open to them. In any case, it should support either mode of operation now. Let me know if you find a way to break it!
