### ISSUE TITLE
esmf-mpi/8.3.0 build issue 

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/spack-gust#21]
When I try to build cesm with this module I get an error:
  /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lxerces-c

I think that the solution is to build esmf without the xerces library which we do not use. 
Another issue is that with the intel compiler I am using mkl and not libsci but esmf is
built with libsci and so I get another error:
  /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lsci_intel
  I can work around this for now by using libsci instead of mkl

**Comment by jedwards4b** [comment]
The same error with xerces was found with a gnu build.

**Comment by vanderwb** [comment]
Hi @jedwards4b - thanks for the ping on this. I believe the xerces error should be resolved for new CESM builds by the changes announced in the Gust Slack channel this morning. When you have a chance, please rebuild your case and see if the -lxerces-c problem is gone.

The use of libsci will stick around *for now*, but if this becomes blocking for your work let me know and I can build an alternate ESMF for you.

**Comment by jedwards4b** [comment]
The xerces-c problem is gone.  Thanks!
