### ISSUE TITLE
Modules aren't loaded completely in shells

### ISSUE THREAD

**Issue by apcraig** [NCAR/spack-gust#24]
When I login to gust, I can do "module avail" and see what's there. 

If I then type csh or tcsh and do "module avail", many of the modules are not shown.  I still have the same default modules loaded (module list), but don't seem to access to other modules when starting up a new shell.

**Comment by apcraig** [comment]
And the default shell is bash which I don't want to be working in.

**Comment by roryck** [comment]
I believe this is simply because the module initialization is being skipped because the tcsh you are starting is not a login shell. After starting tcsh try:

source /glade/u/apps/gust/22.08b/spack/opt/spack/lmod/8.7.2/gcc/7.5.0/lmod/lmod/init/tcsh
module reset
module avail

**Comment by apcraig** [comment]
That seems to work @roryck, thanks.

**Comment by roryck** [comment]
Good to hear. Also, you can set tcsh as your login shell through sam.ucar.edu --> user menu --> preferences 
And use the Edit button in the login shell box.
