### ISSUE TITLE
Additional Container Runtimes

### ISSUE THREAD

**Issue by matthewsucar** [NCAR/spack-gust#27]
Users showed significant interest in Docker support. It'd be nice if we could include Docker and/or Podman. Podman has better rootless support but Docker should be possible too. We may need to stub out the subuid/subgid stuff, not sure. 

https://docs.docker.com/engine/security/rootless/

I can provide instructions for making Podman work if Spack doesn't already have it. I haven't tried to make Docker work yet.

**Comment by benkirk** [comment]
Spack does seem to have a podman recipe, but not docker best I can tell so far.

Do you think we can satisfy the use cases with local/laptop Docker + Podman on the HPC systems?  Seems like that is part of the podman design goal, so it's simply workflow education...

**Comment by vanderwb** [comment]
podman is installed as of [cacb43f](https://github.com/NCAR/spack-gust/commit/cacb43f171d707cdfe33cb8bff7e9c57c4e7bddb)
