### ISSUE TITLE
Module issue with cray-mpich when starting a session on compute node.

### ISSUE THREAD

**Issue by roryck** [NCAR/spack-gust#3]
Login node module environment:
1) ncarenv/22.08 (S)   2) craype/2.7.17 (S)   3) cuda/11.7

submitted interactive job with:
qsub -I -l select=1:ngpus=4 -A SCSG0001 -q system

Received error:
Lmod has detected the following error:  /glade/u/apps/gust/modules/22.08/cce/14.0.2/cray-mpich/8.1.18: (cray-mpich/8.1.18): couldn't read file
"/opt/cray/pe/mpich/8.1.18/.mpich_set_paths_stub": no such file or directory

**Comment by vanderwb** [comment]
Closed after conversation with @jbaksta
