### ISSUE TITLE
lmod path simplification

### ISSUE THREAD

**Issue by jedwards4b** [NCAR/spack-gust#39]
Because cesm uses a python interface to lmod we need the path in our configuration file, the current path on gust is:
/glade/u/apps/gust/default/spack/opt/spack/lmod/8.7.14/gcc/7.5.0/lmod/8.7.14/

If that path changes as just happened with the update to ncarenv/22.12 we need to change our configuration in order to work again.    It would be nice if this were in an environment variable or used links so that a correct path were always available.

I tried using LMOD_ROOT which is set to /usr/share/lmod but it turns out that this path is not available on compute nodes.

**Comment by vanderwb** [comment]
Hey @jedwards - now that `LMOD_ROOT` should be working properly, is there anything else you need here?

**Comment by jedwards4b** [comment]
No - that will work fine.  Thanks
