### ISSUE TITLE
Request display

### ISSUE THREAD

**Issue by katiedagon** [NCAR/spack-gust#50]
Request to add [display](https://imagemagick.org/script/display.php) (or an alternate command line tool) to Gust for viewing png and pdf files.

**Comment by vanderwb** [comment]
Thanks Katie. I'm looking into it now.

**Comment by katiedagon** [comment]
Thanks Brian!

**Comment by vanderwb** [comment]
@katiedagon - `display` along with other ImageMagick utilities should be available now in your default environment on Gust (with the `ncarenv/23.04` module loaded). Let me know if you encounter any issues.

**Comment by katiedagon** [comment]
Thanks so much for getting this installed so quickly, @vanderwb. I think this will be quite helpful for our workflow on gust/derecho.
