### ISSUE TITLE
Add conflicts for serial and MPI versions of software

### ISSUE THREAD

**Issue by vanderwb** [NCAR/spack-gust#9]
Jim: "when I load netcdf-mpi it does not unload netcdf and hdf5"

**Comment by vanderwb** [comment]
@jedwards4b Conflicts should be in place now for netcdf and hdf5 as of f69bc09.

**Comment by jedwards4b** [comment]
@vanderwb I find this a bit confusing:
```
module reset
Running "module reset". Resetting modules to system default. The following $MODULEPATH directories have been removed: None
[gust1] jedwards@gust01:~> module load netcdf-mpi
Lmod has detected the following error:  Cannot load module "hdf5-mpi/1.12.2" because these module(s) are loaded:
   hdf5

While processing the following module(s):
    Module fullname   Module Filename
    ---------------   ---------------
    hdf5-mpi/1.12.2   /glade/u/apps/gust/modules/22.08/cray-mpich/8.1.18-jejyfue/cce/14.0.2/hdf5-mpi/1.12.2.lua
    netcdf-mpi/4.8.1  /glade/u/apps/gust/modules/22.08/cray-mpich/8.1.18-jejyfue/cce/14.0.2/netcdf-mpi/4.8.1.lua

```

**Comment by jedwards4b** [comment]
Maybe it's okay - if I module rm netcdf first it also removes the hdf5.

**Comment by vanderwb** [comment]
Yes - I agree. It would be nice if Lmod noticed the netcdf conflict before the hdf5 one, but I suppose that's a consequence of its order of operations. It handles the `module swap netcdf netcdf-mpi` case gracefully though, which I think is the important part.
